sudo: false
language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
before_script:
  - npm prune
